### PR TITLE
task4: add test scripts

### PR DESCRIPTION
**Pull request by miri64**
Note, that due to https://github.com/RIOT-OS/RIOT/issues/10338 tasks 7 and 8 might fail randomly.

### CODE REVIEW

**Comment by miri64** [comment]
(also incompatible to #6 ;-))

**Comment by jia200x** [comment]
since this branch is still in development, let's do it that way ;)

**Comment by jia200x** [comment]
I can fix that :)

**Comment by miri64** [comment]
I'm in those scripts anyway at the moment, so I can do it ;-)

**Comment by jia200x** [comment]
ok, even better :)

**Pull request merged**
